language: go

go:
  - "1.11.5"

install:
  - make tools

go_import_path: github.com/aslakknutsen/istio-workspace

jobs:
  include:
    - stage: test
      script: make
    - stage: e2e-tests
      script: make format # dummy for now
