# Force dep to vendor the code generators, which aren't imported just used at dev time.
required = [
  "k8s.io/code-generator/cmd/defaulter-gen",
  "k8s.io/code-generator/cmd/deepcopy-gen",
  "k8s.io/code-generator/cmd/conversion-gen",
  "k8s.io/code-generator/cmd/client-gen",
  "k8s.io/code-generator/cmd/lister-gen",
  "k8s.io/code-generator/cmd/informer-gen",
  "k8s.io/gengo/args",
]

[prune]
  go-tests = true
  non-go = true

  [[prune.project]]
    name = "k8s.io/code-generator"
    non-go = false

  [[prune.project]]
    name = "k8s.io/gengo"

# Constraints
[[constraint]]
  name = "k8s.io/code-generator"
  version = "kubernetes-1.16.0"

[[constraint]]
  name = "k8s.io/api"
  version = "kubernetes-1.16.0"

[[constraint]]
  name = "k8s.io/apiextensions-apiserver"
  version = "kubernetes-1.16.0"

[[constraint]]
  name = "k8s.io/apimachinery"
  version = "kubernetes-1.16.0"

[[constraint]]
  name = "k8s.io/client-go"
  version = "kubernetes-1.16.0"

[[constraint]]
  name = "sigs.k8s.io/controller-runtime"
  version = "=v0.5.0"

[[constraint]]
  name = "istio.io/client-go"
  branch = "release-1.4"

[[constraint]]
  name = "github.com/operator-framework/operator-sdk"
  version = "=0.17.2"

[[constraint]]
  name = "github.com/openshift/api"
  branch = "release-4.3"

[[constraint]]
  name = "github.com/go-cmd/cmd"
  version = "=1.1.0"

[[constraint]]
  name = "github.com/hashicorp/go-multierror"
  version = "=v1.1.0"

[[constraint]]
  name = "github.com/onsi/gomega"
  version = "=1.10.1"

[[constraint]]
  name = "github.com/onsi/ginkgo"
  version = "=1.14.1"

[[constraint]]
  name = "github.com/joho/godotenv"
  version = "=v1.3.0"

[[constraint]]
  name = "go.uber.org/goleak"
  branch = "master"

[[constraint]]
  name = "github.com/sabhiram/go-gitignore"
  branch = "master"

[[constraint]]
  name = "github.com/spf13/viper"
  version = "=v1.7.1"

[[constraint]]
  name = "github.com/spf13/cobra"
  version = "=v1.0.0"

[[constraint]]
  name = "github.com/google/shlex"
  branch = "master"

[[constraint]]
  name = "gopkg.in/h2non/gock.v1"
  version = "=v1.0.15"

[[constraint]]
  name = "github.com/google/go-github"
  version = "=v32.1.0"

# Overrides
[[override]]
  name = "k8s.io/kube-openapi"
  branch = "release-1.16"

[[override]]
  name = "github.com/coreos/prometheus-operator"
  version = "=v0.34.0"

[[override]]
  name = "istio.io/api"
  branch = "release-1.4"

## Locking k8s/{klog,utils,gengo} to before klog@v2.0.0 as otherwise we are facing https://github.com/kubernetes/klog/issues/138
[[override]]
  name = "k8s.io/utils"
  revision = "5770800c2500f42361fa90f2d5df947d2c5db138"

[[override]]
  name = "k8s.io/klog"
  version = "v2.3.0"

[[override]]
  name = "k8s.io/gengo"
  revision = "793b05dca9b871fdc15aeaff1f201e141ef5afa7"

## Workaround for https://github.com/golang/dep/issues/1799 - see https://github.com/golang/dep/issues/1799#issuecomment-381190029
## Otherwise ginkgo/gomega won't be pulled in
[[override]]
  name = "gopkg.in/fsnotify.v1"
  source = "https://github.com/fsnotify/fsnotify.git"
