# Force dep to vendor the code generators, which aren't imported just used at dev time.
required = [
  "k8s.io/code-generator/cmd/defaulter-gen",
  "k8s.io/code-generator/cmd/deepcopy-gen",
  "k8s.io/code-generator/cmd/conversion-gen",
  "k8s.io/code-generator/cmd/client-gen",
  "k8s.io/code-generator/cmd/lister-gen",
  "k8s.io/code-generator/cmd/informer-gen",
  "k8s.io/gengo/args",
]

[prune]
  go-tests = true
  non-go = true

  [[prune.project]]
    name = "k8s.io/code-generator"
    non-go = false

[[override]]
  name = "k8s.io/code-generator"
  # revision for tag "kubernetes-1.14.6"
  revision = "50b561225d70b3eb79a1faafd3dfe7b1a62cbe73"

[[override]]
  name = "k8s.io/api"
  # revision for tag "kubernetes-1.14.6"
  revision = "e3a6b8045b0b303430f6d0c261fd9e35be50800e"

[[override]]
  name = "k8s.io/apiextensions-apiserver"
  # revision for tag "kubernetes-1.14.6"
  revision = "e49a3471dba57c6a6b7437fae6897655eb3d6982"

[[override]]
  name = "k8s.io/apimachinery"
  # revision for tag "kubernetes-1.14.6"
  revision = "a9f1d8a9c10182d101acf19b5145c3d4e9299adb"

[[override]]
  name = "k8s.io/client-go"
  # revision for tag "kubernetes-1.14.6"
  revision = "7e43eff7c80aab1d14728f84248931b9db28bdc0"

[[override]]
  name = "github.com/coreos/prometheus-operator"
  version = "=v0.30.0"

[[override]]
  name = "sigs.k8s.io/controller-runtime"
  version = "=v0.3.0"

[[override]]
  name = "istio.io/api"
  source = "https://github.com/aslakknutsen/istio-api.git"
  branch = "istio-8772"

[[constraint]]
  name = "github.com/operator-framework/operator-sdk"
  version = "=0.12.0"

[[override]]
  name = "k8s.io/kube-openapi"
  revision = "0cf8f7e6ed1d2e3d47d02e3b6e559369af24d803"

# Workaround for https://github.com/golang/dep/issues/1799
# Otherwise ginkgo/gomega won't be pulled in
[[override]]
  name = "gopkg.in/fsnotify.v1"
  source = "https://github.com/fsnotify/fsnotify.git"

[[constraint]]
  name = "github.com/openshift/api"
  version = "=v3.9.0"

[[constraint]]
  name = "github.com/go-cmd/cmd"
  version = "=1.1.0"

[[constraint]]
  name = "github.com/hashicorp/go-multierror"
  version = "=v1.0.0"

[[constraint]]
  name = "github.com/onsi/gomega"
  version = "=1.7.1"

[[constraint]]
  name = "github.com/onsi/ginkgo"
  version = "=1.10.3"

[[constraint]]
  name = "go.uber.org/goleak"
  branch = "master"

[[constraint]]
  name = "github.com/sabhiram/go-gitignore"
  branch = "master"

[[constraint]]
  name = "github.com/spf13/viper"
  version = "=v1.6.1"

[[constraint]]
  name = "github.com/spf13/cobra"
  version = "=v0.0.5"

[[constraint]]
  name = "github.com/google/shlex"
  branch = "master"

[[constraint]]
  name = "gopkg.in/h2non/gock.v1"
  version = "=v1.0.15"

[[constraint]]
  name = "github.com/google/go-github"
  version = "=v28.1.1"
