kind: Template
apiVersion: template.openshift.io/v1
parameters:
  - name: IKE_DOCKER_REGISTRY
    description: "Docker registry where deployed image is available"
    required: true
    value: quay.io
  - name: IKE_DOCKER_REPOSITORY
    description: "Repository in which the image can be found"
    required: true
    value: maistra
  - name: IKE_IMAGE_NAME
    description: "The name of the image with ike binary"
    required: true
    value: istio-workspace
  - name: IKE_IMAGE_TAG
    description: "The tag of the image to be used"
    required: true
    value: latest
  - name: WATCH_NAMESPACE
    description: "The namespace to watch. Leave empty for cluster wide watch."
    required: false
    value: ""
objects:
  - kind: Deployment
    apiVersion: apps/v1
    metadata:
      name: istio-workspace
      labels:
        app: istio-workspace
        version: ${IKE_VERSION}
    spec:
      replicas: 1
      selector:
        matchLabels:
          app: istio-workspace
          version: ${IKE_VERSION}
      template:
        metadata:
          name: istio-workspace
          labels:
            app: istio-workspace
            version: ${IKE_VERSION}
        spec:
          serviceAccountName: istio-workspace
          containers:
            - name: istio-workspace
              image: ${IKE_DOCKER_REGISTRY}/${IKE_DOCKER_REPOSITORY}/${IKE_IMAGE_NAME}:${IKE_IMAGE_TAG}
              command:
                - ike
              args:
                - serve
              imagePullPolicy: Always
              env:
                - name: WATCH_NAMESPACE
                  value: "${WATCH_NAMESPACE}"
                - name: POD_NAME
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.name
                - name: OPERATOR_NAME
                  value: "istio-workspace"
