name: session-url
      taskRef:
        name: ike-session-url
        kind: Task
      runAfter:
        - wait-for-sync
      params:
        - name: session
          value: $(params.git-pr-head-ref)
        - name: namespace
          value: workspace-demo